var config = {
  path=r'C:\Users\v-yomaja\Documents\IBM-DS\Datasets\Geospatial_Coordinates.csv'
  MY_API_TOKEN : '35NQZC1OIT22IYQ2CRHNDIKEWRXTT0NZBVV1QOYAZHKUVU4H',
  SECRET_API_KEY : 'IWW0ENDG2EWFY1Y50GQJG3S3NN32SDORSZMMVQ1MOOOX1TK2',
}
